# Generated by Django 5.1.6 on 2025-04-25 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 10, 59, 11, 105753, tzinfo=datetime.timezone.utc)),
        ),
    ]
