# Generated by Django 5.1.6 on 2025-05-06 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalresult',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.practitioner'),
        ),
        migrations.AddField(
            model_name='ecg',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.practitioner'),
        ),
        migrations.AddField(
            model_name='examination',
            name='bp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='examination',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.practitioner'),
        ),
        migrations.AddField(
            model_name='labresults',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.practitioner'),
        ),
        migrations.AddField(
            model_name='medicalscan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.practitioner'),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.practitioner'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.practitioner'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='prediction_type',
            field=models.CharField(choices=[('ecg', 'ECG Reading Images'), ('mri', 'MRI Scan'), ('ct_scans', 'CT-Scan'), ('x_ray', 'Chest X-Ray'), ('lab', 'Lab Test Predictions'), ('clinic', 'Clinical Assessment Predictions'), ('exam', 'Examination Stage Prediction')], default='ecg', max_length=250),
        ),
        migrations.AlterField(
            model_name='clinicalresult',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient'),
        ),
        migrations.AlterField(
            model_name='ecg',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient'),
        ),
        migrations.AlterField(
            model_name='ecg',
            name='scan_dat',
            field=models.FileField(upload_to='data/scans/ecg'),
        ),
        migrations.AlterField(
            model_name='ecg',
            name='scan_hea',
            field=models.FileField(upload_to='data/scans/ecg'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient'),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient'),
        ),
        migrations.AlterField(
            model_name='medicalscan',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('I', 'Intersex'), ('O', 'Other')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='serial_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient'),
        ),
        migrations.AlterField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient'),
        ),
        migrations.AlterField(
            model_name='report',
            name='served_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.practitioner'),
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('patient', 'prediction_type', 'date')},
        ),
    ]
