# Generated by Django 5.1.6 on 2025-05-03 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 3, 5, 21, 37, 216791, tzinfo=datetime.timezone.utc)),
        ),
    ]
