# Generated by Django 5.1.6 on 2025-04-25 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_practitioner_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 11, 12, 3, 202449, tzinfo=datetime.timezone.utc)),
        ),
    ]
