# Generated by Django 5.1.6 on 2025-05-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_clinicalresult_created_by_ecg_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicalresult',
            name='diabetes',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='clinicalresult',
            name='hbp',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='bp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='examination',
            name='family_history',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='smoking_habits',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='chol_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='crp_level',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='fasting_blood_sugar',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='high_ldl',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='homo_level',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='low_hdl',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='trig_level',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1),
        ),
    ]
