# Generated by Django 5.1.6 on 2025-05-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_customuser_gender_customuser_sex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred_type', models.CharField(max_length=100)),
                ('serial_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient')),
            ],
        ),
    ]
