# Generated by Django 5.1.6 on 2025-05-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_predtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalresult',
            name='diabetes',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='clinicalresult',
            name='hbp',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='alc_habits',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Moderate'), ('High', 'High')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='ex_habits',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Moderate'), ('High', 'High')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='family_history',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='smoking_habits',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='stress_levels',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Moderate'), ('High', 'High')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='examination',
            name='sugar_cons',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Moderate'), ('High', 'High')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='high_ldl',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='low_hdl',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=50),
        ),
    ]
