# Generated by Django 5.1.6 on 2025-06-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_prediction_prediction_type_delete_predtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='abdominal_circ',
            field=models.FloatField(default=91.0),
        ),
        migrations.AddField(
            model_name='examination',
            name='height',
            field=models.FloatField(default=1.73),
        ),
        migrations.AddField(
            model_name='examination',
            name='weight',
            field=models.FloatField(default=77.8),
        ),
        migrations.AddField(
            model_name='labresults',
            name='hdl_reading',
            field=models.FloatField(default=47.0),
        ),
        migrations.AddField(
            model_name='prediction',
            name='risk_conf_score',
            field=models.FloatField(default=0.0),
        ),
    ]
